version: 2

# Circle jobs
jobs:

  # Verify code then run unit and integration tests
  test-node-8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm ci
      - run: make verify
      - run: make test

  test-node-9:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: npm ci
      - run: make verify
      - run: make test

  test-node-10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
      - run: make verify
      - run: make test

  test-node-11:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run: npm ci
      - run: make verify
      - run: make test

  # Publish the module to npm
  publish:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Authenticate with npm
          command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ${HOME}/.npmrc
      - run: npm version --git-tag-version=false
      - run: npm publish --access=public

# Circle workflows
workflows:
  version: 2
  test-and-publish:
    jobs:
      - test-node-8:
          filters:
            tags:
              only: /v.*/
      - test-node-9:
          filters:
            tags:
              only: /v.*/
      - test-node-10:
          filters:
            tags:
              only: /v.*/
      - test-node-11:
          filters:
            tags:
              only: /v.*/
      - publish:
          requires:
            - test-node-8
            - test-node-9
            - test-node-10
            - test-node-11
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
