name: npm audit fix

on:
  schedule:
    - cron: 0 10 * * * # Runs at 10:00 UTC every day

jobs:
  npm-audit-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JakeChampion/npm-audit-fix-action@master
        with:
          github_token: ${{ secrets.ORIGAMI_GITHUB_TOKEN }}
